#!/bin/sh
#
# Definitions for the JavaScript interpreter testing environment.
#

js="../js"

# Check that $srcdir is set correctly.
test -f $srcdir/defs || {
  echo "defs: installation error" 1>&2
  exit 1
}
